In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('diabetes.csv')

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

Before training any nural network we need to scaling all of them.

In [ ]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,random_state=42)

Now this is tim eto make a model (Nueral Network)

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [ ]:
model = Sequential()
model.add(Dense(24,activation='relu',input_dim=x_train.shape[1]))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer = 'adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.fit(x_train, y_train,batch_size=32, epochs=25, validation_data=(x_test,y_test))

Epoch 1/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.5226 - loss: 0.6941 - val_accuracy: 0.6354 - val_loss: 0.6489
Epoch 2/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6424 - loss: 0.6400 - val_accuracy: 0.6719 - val_loss: 0.6146
Epoch 3/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6979 - loss: 0.5995 - val_accuracy: 0.7083 - val_loss: 0.5911
Epoch 4/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7326 - loss: 0.5708 - val_accuracy: 0.7188 - val_loss: 0.5737
Epoch 5/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7344 - loss: 0.5481 - val_accuracy: 0.7135 - val_loss: 0.5609
Epoch 6/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7552 - loss: 0.5313 - val_accuracy: 0.6979 - val_loss: 0.5510
Epoch 7/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7517 - loss: 0.5171 - val_accuracy: 0.6979 - val_loss: 0.5431
Epoch 8/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7587 - loss: 0.5059 - val_accuracy: 0.7083 - val_loss: 0.5368
Epoch 9/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7569 - loss: 0.4962 - val_accuracy: 0.7240 - val_loss: 0.5316
Epoch 10/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7639 - loss: 0.4884 - val_accuracy: 0.7240 - val_loss: 0.5277
Epoch 11/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7691 - loss: 0.4813 - val_accuracy: 0.7240 - val_loss: 0.5250
Epoch 12/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7674 - loss: 0.4758 - val_accuracy: 0.7292 - val_loss: 0.5234
Epoch 13/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7708 - loss: 0.4704 - val_accuracy: 0.7240 - val_loss: 0.5219
Epoch 14/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7726 - loss: 0.4665 - val_accuracy: 0.7344 - val_loss: 0.5204
Epoch 15/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4625 - val_accuracy: 0.7292 - val_loss: 0.5199
Epoch 16/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.4591 - val_accuracy: 0.7240 - val_loss: 0.5191
Epoch 17/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7830 - loss: 0.4560 - val_accuracy: 0.7240 - val_loss: 0.5195
Epoch 18/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7865 - loss: 0.4539 - val_accuracy: 0.7292 - val_loss: 0.5201
Epoch 19/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7917 - loss: 0.4507 - val_accuracy: 0.7292 - val_loss: 0.5197
Epoch 20/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7917 - loss: 0.4486 - val_accuracy: 0.7292 - val_loss: 0.5207
Epoch 21/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4462 - val_accuracy: 0.7292 - val_loss: 0.5206
Epoch 22/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7917 - loss: 0.4443 - val_accuracy: 0.7292 - val_loss: 0.5222
Epoch 23/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7951 - loss: 0.4426 - val_accuracy: 0.7344 - val_loss: 0.5227
Epoch 24/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7986 - loss: 0.4411 - val_accuracy: 0.7292 - val_loss: 0.5233
Epoch 25/25
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7969 - loss: 0.4393 - val_accuracy: 0.7292 - val_loss: 0.5245

How to automate the model to find out the appropiate parametres for out model...

1. How to selelct appropiate Optimizer
2. Number of nodes in a layer
3. How to select number of layes
4. All in one

In [ ]:
# If you don't have keras tuner first install it.
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 2.8 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
import keras_tuner as kt

In [ ]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(24,activation='relu',input_dim=x_train.shape[1]))
  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer',['adam','rmsprop','sgd','adagrad'])
  model.compile(optimizer = optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data =(x_test,y_test),verbose = 1)

In [ ]:
tuner.get_best_hyperparameters(num_trials = 3)[0].values

{'optimizer': 'rmsprop'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 24)             │           216 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            25 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 241 (964.00 B)

 Trainable params: 241 (964.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch = 6, validation_data=(x_test,y_test))
#initial_epoch means we initially train the model till epochs=5 i need to retain the information

Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7587 - loss: 0.5466 - val_accuracy: 0.7448 - val_loss: 0.5584
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.5228 - val_accuracy: 0.7500 - val_loss: 0.5451
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7812 - loss: 0.5067 - val_accuracy: 0.7448 - val_loss: 0.5347
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7847 - loss: 0.4936 - val_accuracy: 0.7396 - val_loss: 0.5271
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7830 - loss: 0.4831 - val_accuracy: 0.7448 - val_loss: 0.5221
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7882 - loss: 0.4752 - val_accuracy: 0.7396 - val_loss: 0.5189
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7917 - loss: 0.4684 - val_accuracy: 0.7396 - val_loss: 0.5162
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4625 - val_accuracy: 0.7396 - val_loss: 0.5142
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4577 - val_accuracy: 0.7396 - val_loss: 0.5130
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7951 - loss: 0.4535 - val_accuracy: 0.7396 - val_loss: 0.5124
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7951 - loss: 0.4499 - val_accuracy: 0.7344 - val_loss: 0.5122
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4469 - val_accuracy: 0.7448 - val_loss: 0.5124
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7882 - loss: 0.4441 - val_accuracy: 0.7448 - val_loss: 0.5124
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4418 - val_accuracy: 0.7448 - val_loss: 0.5128
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7934 - loss: 0.4398 - val_accuracy: 0.7396 - val_loss: 0.5131
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4379 - val_accuracy: 0.7292 - val_loss: 0.5136
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4363 - val_accuracy: 0.7292 - val_loss: 0.5141
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8003 - loss: 0.4347 - val_accuracy: 0.7292 - val_loss: 0.5149
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4332 - val_accuracy: 0.7292 - val_loss: 0.5154
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4318 - val_accuracy: 0.7344 - val_loss: 0.5163
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4306 - val_accuracy: 0.7344 - val_loss: 0.5172
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7934 - loss: 0.4295 - val_accuracy: 0.7344 - val_loss: 0.5180
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4283 - val_accuracy: 0.7344 - val_loss: 0.5192
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4277 - val_accuracy: 0.7292 - val_loss: 0.5204
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7986 - loss: 0.4263 - val_accuracy: 0.7292 - val_loss: 0.5213
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4257 - val_accuracy: 0.7344 - val_loss: 0.5222
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4249 - val_accuracy: 0.7344 - val_loss: 0.5232
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4239 - val_accuracy: 0.7344 - val_loss: 0.5235
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7951 - loss: 0.4233 - val_accuracy: 0.7344 - val_loss: 0.5238
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7951 - loss: 0.4226 - val_accuracy: 0.7448 - val_loss: 0.5245
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7951 - loss: 0.4219 - val_accuracy: 0.7396 - val_loss: 0.5256
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7969 - loss: 0.4210 - val_accuracy: 0.7396 - val_loss: 0.5262
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7969 - loss: 0.4204 - val_accuracy: 0.7396 - val_loss: 0.5279
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4198 - val_accuracy: 0.7396 - val_loss: 0.5285
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.7934 - loss: 0.4194 - val_accuracy: 0.7396 - val_loss: 0.5291
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7969 - loss: 0.4186 - val_accuracy: 0.7448 - val_loss: 0.5296
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7934 - loss: 0.4182 - val_accuracy: 0.7396 - val_loss: 0.5305
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7986 - loss: 0.4174 - val_accuracy: 0.7396 - val_loss: 0.5309
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7969 - loss: 0.4172 - val_accuracy: 0.7396 - val_loss: 0.5312
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8003 - loss: 0.4165 - val_accuracy: 0.7396 - val_loss: 0.5317
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8021 - loss: 0.4162 - val_accuracy: 0.7396 - val_loss: 0.5325
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7969 - loss: 0.4154 - val_accuracy: 0.7396 - val_loss: 0.5330
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7969 - loss: 0.4152 - val_accuracy: 0.7396 - val_loss: 0.5334
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8003 - loss: 0.4144 - val_accuracy: 0.7448 - val_loss: 0.5341
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7986 - loss: 0.4142 - val_accuracy: 0.7448 - val_loss: 0.5345
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7969 - loss: 0.4135 - val_accuracy: 0.7448 - val_loss: 0.5345
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7969 - loss: 0.4132 - val_accuracy: 0.7448 - val_loss: 0.5350
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7969 - loss: 0.4129 - val_accuracy: 0.7396 - val_loss: 0.5354
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8003 - loss: 0.4124 - val_accuracy: 0.7396 - val_loss: 0.5359
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4117 - val_accuracy: 0.7396 - val_loss: 0.5361
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8003 - loss: 0.4112 - val_accuracy: 0.7396 - val_loss: 0.5365
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7986 - loss: 0.4110 - val_accuracy: 0.7448 - val_loss: 0.5368
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4106 - val_accuracy: 0.7448 - val_loss: 0.5370
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4101 - val_accuracy: 0.7448 - val_loss: 0.5374
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4100 - val_accuracy: 0.7448 - val_loss: 0.5380
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8038 - loss: 0.4092 - val_accuracy: 0.7500 - val_loss: 0.5384
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8056 - loss: 0.4090 - val_accuracy: 0.7552 - val_loss: 0.5389
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8038 - loss: 0.4089 - val_accuracy: 0.7500 - val_loss: 0.5390
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8003 - loss: 0.4083 - val_accuracy: 0.7500 - val_loss: 0.5391
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4081 - val_accuracy: 0.7500 - val_loss: 0.5394
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4072 - val_accuracy: 0.7500 - val_loss: 0.5395
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4074 - val_accuracy: 0.7500 - val_loss: 0.5397
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4070 - val_accuracy: 0.7500 - val_loss: 0.5399
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4061 - val_accuracy: 0.7500 - val_loss: 0.5398
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8090 - loss: 0.4062 - val_accuracy: 0.7500 - val_loss: 0.5406
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8038 - loss: 0.4059 - val_accuracy: 0.7500 - val_loss: 0.5413
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8073 - loss: 0.4053 - val_accuracy: 0.7552 - val_loss: 0.5413
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4054 - val_accuracy: 0.7552 - val_loss: 0.5413
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4050 - val_accuracy: 0.7552 - val_loss: 0.5420
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8056 - loss: 0.4046 - val_accuracy: 0.7500 - val_loss: 0.5419
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4039 - val_accuracy: 0.7500 - val_loss: 0.5424
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8073 - loss: 0.4040 - val_accuracy: 0.7448 - val_loss: 0.5423
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4033 - val_accuracy: 0.7448 - val_loss: 0.5418
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4035 - val_accuracy: 0.7448 - val_loss: 0.5419
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8108 - loss: 0.4027 - val_accuracy: 0.7500 - val_loss: 0.5423
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8108 - loss: 0.4024 - val_accuracy: 0.7500 - val_loss: 0.5428
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8108 - loss: 0.4021 - val_accuracy: 0.7500 - val_loss: 0.5426
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4018 - val_accuracy: 0.7500 - val_loss: 0.5429
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8142 - loss: 0.4012 - val_accuracy: 0.7500 - val_loss: 0.5427
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4012 - val_accuracy: 0.7500 - val_loss: 0.5431
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8142 - loss: 0.4005 - val_accuracy: 0.7500 - val_loss: 0.5435
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.8160 - loss: 0.4005 - val_accuracy: 0.7500 - val_loss: 0.5437
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.8090 - loss: 0.3999 - val_accuracy: 0.7500 - val_loss: 0.5440
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8142 - loss: 0.3997 - val_accuracy: 0.7500 - val_loss: 0.5442
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8177 - loss: 0.3993 - val_accuracy: 0.7500 - val_loss: 0.5448
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3990 - val_accuracy: 0.7500 - val_loss: 0.5445
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3985 - val_accuracy: 0.7500 - val_loss: 0.5450
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8177 - loss: 0.3983 - val_accuracy: 0.7500 - val_loss: 0.5453
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8177 - loss: 0.3981 - val_accuracy: 0.7500 - val_loss: 0.5454
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3982 - val_accuracy: 0.7448 - val_loss: 0.5458
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3973 - val_accuracy: 0.7500 - val_loss: 0.5455
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.3974 - val_accuracy: 0.7500 - val_loss: 0.5464
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3969 - val_accuracy: 0.7500 - val_loss: 0.5470
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8212 - loss: 0.3965 - val_accuracy: 0.7448 - val_loss: 0.5473

In [ ]:
#trying to find best number of neurons in one hidden layer
def build_model(hp):
  model  = Sequential()
  units = hp.Int('units',min_value = 8,max_value = 128,step=8) # number of neurons will be taken = 8,16,24,32,40......
  model.add(Dense(units=units,activation='relu',input_dim=x_train.shape[1]))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer = 'rmsprop',loss = 'binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory='units_tuning',
    project_name='units_tuning_project' # Use a new project name
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test),verbose=1)

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7135416865348816

Best val_accuracy So Far: 0.765625
Total elapsed time: 00h 00m 13s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'units': 104}

In [ ]:
#trying to find best number of hidden layers in our model
def build_model(hp):
  model = Sequential()
  model.add(Dense(104,activation='relu',input_dim=8))
  for i in range(hp.Int('num_layer', min_value=1,max_value=10)):
    model.add(Dense(104,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer = 'rmsprop',loss = 'binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective ="val_accuracy",
                        max_trials=2,
                        directory='layers',
                        project_name='number_of_layers')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test),verbose=1)

Trial 2 Complete [00h 00m 04s]
val_accuracy: 0.765625

Best val_accuracy So Far: 0.765625
Total elapsed time: 00h 00m 10s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layer': 4}

Now we are doing more than one thing

In [ ]:
def build_model(hp):
  model = Sequential()

  counter = 0
  for i in range(hp.Int('num_layer', min_value=1,max_value=10)):
    if counter == 0:
      model.add(
          Dense(
              hp.Int('units'+str(i),min_value = 8,max_value = 128,step=8),
              activation=hp.choice('activation' + str(i)), values=['relu','sigmoid','tanh']),
              input_dims=8)
    else:
       model.add(
          Dense(
              hp.Int('units'+str(i),min_value = 8,max_value = 128,step=8),
              activation=hp.choice('activation' + str(i)), values=['relu','sigmoid','tanh']))
    counter += 1

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer = 'rmsprop',loss = 'binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner= kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory = "all",
    project_name = "neurons_&_nodes"
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test),verbose=1)

Trial 5 Complete [00h 00m 07s]
val_accuracy: 0.703125

Best val_accuracy So Far: 0.765625
Total elapsed time: 00h 00m 21s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layer': 3,
 'units0': 120,
 'activation0': 'tanh',
 'units1': 8,
 'activation1': 'relu',
 'units2': 8,
 'activation2': 'relu'}

In [ ]:
final_model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
history = final_model.fit(x_train,y_train,epochs=100,initial_epoch = 6, validation_data=(x_test,y_test))

Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.7795 - loss: 0.4428 - val_accuracy: 0.7552 - val_loss: 0.5291
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4351 - val_accuracy: 0.7552 - val_loss: 0.5323
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7847 - loss: 0.4324 - val_accuracy: 0.7500 - val_loss: 0.5341
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7951 - loss: 0.4295 - val_accuracy: 0.7500 - val_loss: 0.5382
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4276 - val_accuracy: 0.7500 - val_loss: 0.5335
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8021 - loss: 0.4264 - val_accuracy: 0.7448 - val_loss: 0.5379
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7934 - loss: 0.4245 - val_accuracy: 0.7448 - val_loss: 0.5358
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8003 - loss: 0.4232 - val_accuracy: 0.7500 - val_loss: 0.5376
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.4214 - val_accuracy: 0.7448 - val_loss: 0.5354
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8003 - loss: 0.4185 - val_accuracy: 0.7396 - val_loss: 0.5358
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4185 - val_accuracy: 0.7500 - val_loss: 0.5378
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4162 - val_accuracy: 0.7448 - val_loss: 0.5354
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8021 - loss: 0.4139 - val_accuracy: 0.7448 - val_loss: 0.5367
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8142 - loss: 0.4124 - val_accuracy: 0.7552 - val_loss: 0.5374
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8038 - loss: 0.4116 - val_accuracy: 0.7396 - val_loss: 0.5428
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8108 - loss: 0.4091 - val_accuracy: 0.7396 - val_loss: 0.5409
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8090 - loss: 0.4084 - val_accuracy: 0.7396 - val_loss: 0.5392
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.4077 - val_accuracy: 0.7396 - val_loss: 0.5378
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8056 - loss: 0.4052 - val_accuracy: 0.7448 - val_loss: 0.5367
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8073 - loss: 0.4041 - val_accuracy: 0.7396 - val_loss: 0.5437
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.4037 - val_accuracy: 0.7500 - val_loss: 0.5437
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8073 - loss: 0.4015 - val_accuracy: 0.7500 - val_loss: 0.5438
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8003 - loss: 0.3999 - val_accuracy: 0.7500 - val_loss: 0.5402
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8021 - loss: 0.3998 - val_accuracy: 0.7604 - val_loss: 0.5432
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7986 - loss: 0.3995 - val_accuracy: 0.7552 - val_loss: 0.5414
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8038 - loss: 0.3995 - val_accuracy: 0.7552 - val_loss: 0.5443
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8003 - loss: 0.3956 - val_accuracy: 0.7552 - val_loss: 0.5466
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8108 - loss: 0.3963 - val_accuracy: 0.7500 - val_loss: 0.5469
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8090 - loss: 0.3945 - val_accuracy: 0.7500 - val_loss: 0.5492
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8056 - loss: 0.3944 - val_accuracy: 0.7552 - val_loss: 0.5552
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7986 - loss: 0.3937 - val_accuracy: 0.7552 - val_loss: 0.5561
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8056 - loss: 0.3916 - val_accuracy: 0.7604 - val_loss: 0.5492
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8090 - loss: 0.3910 - val_accuracy: 0.7604 - val_loss: 0.5490
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8142 - loss: 0.3904 - val_accuracy: 0.7708 - val_loss: 0.5526
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3894 - val_accuracy: 0.7604 - val_loss: 0.5521
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8108 - loss: 0.3890 - val_accuracy: 0.7604 - val_loss: 0.5566
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8108 - loss: 0.3884 - val_accuracy: 0.7604 - val_loss: 0.5563
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8142 - loss: 0.3877 - val_accuracy: 0.7552 - val_loss: 0.5616
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8125 - loss: 0.3878 - val_accuracy: 0.7604 - val_loss: 0.5600
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8108 - loss: 0.3862 - val_accuracy: 0.7552 - val_loss: 0.5619
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8264 - loss: 0.3844 - val_accuracy: 0.7500 - val_loss: 0.5650
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8090 - loss: 0.3843 - val_accuracy: 0.7396 - val_loss: 0.5681
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8264 - loss: 0.3841 - val_accuracy: 0.7656 - val_loss: 0.5687
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8160 - loss: 0.3832 - val_accuracy: 0.7448 - val_loss: 0.5728
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8108 - loss: 0.3825 - val_accuracy: 0.7552 - val_loss: 0.5616
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8333 - loss: 0.3815 - val_accuracy: 0.7708 - val_loss: 0.5666
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8160 - loss: 0.3819 - val_accuracy: 0.7604 - val_loss: 0.5636
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8125 - loss: 0.3805 - val_accuracy: 0.7656 - val_loss: 0.5612
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8229 - loss: 0.3795 - val_accuracy: 0.7604 - val_loss: 0.5709
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3773 - val_accuracy: 0.7552 - val_loss: 0.5640
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8194 - loss: 0.3768 - val_accuracy: 0.7604 - val_loss: 0.5657
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3769 - val_accuracy: 0.7500 - val_loss: 0.5729
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8142 - loss: 0.3752 - val_accuracy: 0.7552 - val_loss: 0.5611
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8125 - loss: 0.3751 - val_accuracy: 0.7552 - val_loss: 0.5648
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8229 - loss: 0.3747 - val_accuracy: 0.7604 - val_loss: 0.5679
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8247 - loss: 0.3725 - val_accuracy: 0.7604 - val_loss: 0.5677
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3719 - val_accuracy: 0.7500 - val_loss: 0.5701
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8177 - loss: 0.3713 - val_accuracy: 0.7500 - val_loss: 0.5667
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8229 - loss: 0.3710 - val_accuracy: 0.7552 - val_loss: 0.5709
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8177 - loss: 0.3700 - val_accuracy: 0.7500 - val_loss: 0.5704
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8247 - loss: 0.3684 - val_accuracy: 0.7552 - val_loss: 0.5638
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8194 - loss: 0.3691 - val_accuracy: 0.7552 - val_loss: 0.5692
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8299 - loss: 0.3662 - val_accuracy: 0.7708 - val_loss: 0.5731
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8125 - loss: 0.3659 - val_accuracy: 0.7604 - val_loss: 0.5622
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8264 - loss: 0.3650 - val_accuracy: 0.7656 - val_loss: 0.5644
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8177 - loss: 0.3636 - val_accuracy: 0.7604 - val_loss: 0.5679
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8264 - loss: 0.3633 - val_accuracy: 0.7604 - val_loss: 0.5705
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3641 - val_accuracy: 0.7604 - val_loss: 0.5725
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3607 - val_accuracy: 0.7604 - val_loss: 0.5777
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.3619 - val_accuracy: 0.7552 - val_loss: 0.5734
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8177 - loss: 0.3602 - val_accuracy: 0.7656 - val_loss: 0.5752
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8264 - loss: 0.3588 - val_accuracy: 0.7656 - val_loss: 0.5720
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3586 - val_accuracy: 0.7656 - val_loss: 0.5794
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8281 - loss: 0.3587 - val_accuracy: 0.7500 - val_loss: 0.5800
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.3573 - val_accuracy: 0.7656 - val_loss: 0.5733
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8281 - loss: 0.3565 - val_accuracy: 0.7708 - val_loss: 0.5775
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8247 - loss: 0.3554 - val_accuracy: 0.7708 - val_loss: 0.5855
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.3546 - val_accuracy: 0.7552 - val_loss: 0.5859
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8316 - loss: 0.3540 - val_accuracy: 0.7552 - val_loss: 0.5845
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8281 - loss: 0.3519 - val_accuracy: 0.7500 - val_loss: 0.5883
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3515 - val_accuracy: 0.7552 - val_loss: 0.5833
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.3511 - val_accuracy: 0.7552 - val_loss: 0.5857
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8194 - loss: 0.3491 - val_accuracy: 0.7656 - val_loss: 0.5863
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8212 - loss: 0.3498 - val_accuracy: 0.7552 - val_loss: 0.5796
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8229 - loss: 0.3504 - val_accuracy: 0.7656 - val_loss: 0.5887
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.3473 - val_accuracy: 0.7604 - val_loss: 0.5840
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.3468 - val_accuracy: 0.7448 - val_loss: 0.5927
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8264 - loss: 0.3473 - val_accuracy: 0.7448 - val_loss: 0.5933
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8212 - loss: 0.3457 - val_accuracy: 0.7344 - val_loss: 0.5924
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8368 - loss: 0.3444 - val_accuracy: 0.7604 - val_loss: 0.5954
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8281 - loss: 0.3457 - val_accuracy: 0.7448 - val_loss: 0.6050
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8212 - loss: 0.3418 - val_accuracy: 0.7500 - val_loss: 0.5956
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8229 - loss: 0.3447 - val_accuracy: 0.7552 - val_loss: 0.5943
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8316 - loss: 0.3422 - val_accuracy: 0.7604 - val_loss: 0.6052

In [ ]:
def build_model(hp):
  model = Sequential()

  counter = 0
  for i in range(hp.Int('num_layer', min_value=1,max_value=10)):
    if counter == 0:
      model.add(
          Dense(
              hp.Int('units'+str(i),min_value = 8,max_value = 128,step=8),
              activation=hp.Choice('activation' + str(i), ['relu','sigmoid','tanh']),
              input_dim=8))
      model.add(Dropout(hp.Choice('dropout'+str(i), [0.2,0.4,0.5,0.6])))
    else:
       model.add(
          Dense(
              hp.Int('units'+str(i),min_value = 8,max_value = 128,step=8),
              activation=hp.Choice('activation' + str(i), ['relu','sigmoid','tanh'])))
       model.add(Dropout(hp.Choice('dropout'+str(i), [0.2,0.4,0.5,0.6])))
    counter += 1

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer = 'rmsprop',loss = 'binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner= kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory = "all_dropout",
    project_name = "neurons_&_nodes_dropout"
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test),verbose=1)

Trial 5 Complete [00h 00m 05s]
val_accuracy: 0.640625

Best val_accuracy So Far: 0.6979166865348816
Total elapsed time: 00h 00m 23s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layer': 2,
 'units0': 8,
 'activation0': 'relu',
 'dropout0': 0.6,
 'units1': 128,
 'activation1': 'tanh',
 'dropout1': 0.5,
 'units2': 112,
 'activation2': 'sigmoid',
 'dropout2': 0.5,
 'units3': 88,
 'activation3': 'relu',
 'dropout3': 0.6,
 'units4': 96,
 'activation4': 'relu',
 'dropout4': 0.5,
 'units5': 88,
 'activation5': 'relu',
 'dropout5': 0.2}